name: 'python-format-pr'
description: 'Lints PR with black and opens a PR to the target with the fixes'
author: 'jafow <jared.a.fowler@gmail.com>'
inputs: 
  pr-base-branch:
    description: 'base branch target of the pull request'
    default: 'master'
    required: false
outputs:
  fileslist:
    description: 'files formatted'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pr-base-branch }}
